/// Common TLDs for broad availability checks.
///
/// Curated from Cloudflare Registrar's supported TLDs, filtered to those
/// relevant for project/product naming, and ordered by global registration
/// popularity (sources: w3techs.com, ntldstats.com, March 2026).
///
/// Excludes brand TLDs (.google, .amazon), highly niche gTLDs, and TLDs
/// not available through major registrars.
pub const COMMON_TLDS: &[&str] = &[
    // === Tier 1: Major generic TLDs ===
    "com",
    "net",
    "org",
    // === Tier 2: Popular ccTLDs (by global web usage share) ===
    "de",
    "uk",
    "jp",
    "fr",
    "nl",
    "it",
    "br",
    "ru",
    "pl",
    "au",
    "ca",
    "es",
    "in",
    "ch",
    "at",
    "se",
    "no",
    "dk",
    "fi",
    "be",
    "ie",
    "nz",
    "mx",
    "ar",
    "za",
    "kr",
    "tw",
    "hk",
    "sg",
    "pt",
    "cz",
    "hu",
    "ro",
    "gr",
    "il",
    // === Tier 3: Popular new gTLDs (by registrations, >100k) ===
    "xyz",
    "shop",
    "online",
    "store",
    "site",
    "app",
    "live",
    "club",
    "fun",
    "space",
    "dev",
    "tech",
    "life",
    "cloud",
    "world",
    "blog",
    "work",
    "link",
    "digital",
    "art",
    "one",
    "group",
    "studio",
    "agency",
    "email",
    "run",
    "solutions",
    "design",
    "wiki",
    "services",
    "media",
    "news",
    "zone",
    "network",
    // === Tier 4: Tech / developer favorites ===
    "io",
    "ai",
    "co",
    "sh",
    "rs",
    "codes",
    "tools",
    "build",
    "software",
    "engineer",
    "systems",
    "page",
    // === Tier 5: Short / brandable ===
    "me",
    "cc",
    "tv",
    "gg",
    "to",
    "fm",
    "ly",
    "so",
    "is",
    // === Tier 6: Other commonly registered gTLDs ===
    "pro",
    "info",
    "biz",
    "mobi",
    "name",
    "team",
    "games",
    "video",
    "photos",
    "social",
    "health",
    "money",
    "plus",
    "fyi",
    "wtf",
    "lol",
    "land",
    "works",
    "bar",
    "pub",
    "cool",
    "ninja",
    "rocks",
    "host",
    "website",
    // === Tier 7: Regional ===
    "eu",
    "asia",
];
